version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.mirsproject1.integrations:DemoFS2
  packages:
  - name: EdgeMirsProject1
    version: "1.0"
packages:
- name: EdgeMirsProject1
  gitServerName: MirsGit
  gitUrl: https://github.com/mirhussainali/EdgeMirsProject1
  gitUsername: mirhussainali
  gitToken: edge.scaffolding.EdgeMirsProject1.MirsGit.gitToken
  gitBranch: main
